[tasks.docs-clean]
script = [ "rm -rf ./docs" ]

[tasks.docs-copy-template]
script = [ "cp -r .github/docs-template ./docs" ]

[tasks.docs-build]
command = "cargo"
args = [ "doc", "--no-deps", "--lib" ]

[tasks.docs-copy-to-pages]
script = [ "cp -r ./target/doc/* ./docs" ]

[tasks.docs]
dependencies = [
  "docs-clean",
  "docs-copy-template",
  "docs-build",
  "docs-copy-to-pages"
]
