on: workflow_call

name: Release Packaging

env:
  PROJECT_NAME_UNDERSCORE: ${{ vars.PROJECT_NAME_UNDERSCORE }}

jobs:
  build-linux:
    name: Release Packaging Linux
    env:
      ARCH: x86_64-unknown-linux-gnu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ env.ARCH }}
      - name: Release Build
        run: |
          cargo build --release --target=${{ env.ARCH }} \
          && mv target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }} target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }} \
          && mv target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}.rlib target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
      - name: Upload lib Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}
          path: target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}
      - name: Upload bin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
          path: target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
  
  build-windows:
    runs-on: windows-latest
    name: Release Packaging Windows
    env:
      ARCH: x86_64-pc-windows-msvc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ env.ARCH }}
      - name: Release Build
        run: |
          cargo build --release --target=${{ env.ARCH }} ;
          if ($?) {
          mv target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}.exe target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.exe ;
          mv target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}.rlib target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
          }
      - name: Upload lib Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.exe
          path: target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.exe
      - name: Upload bin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib  
          path: target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
  
  build-macos:
    runs-on: macos-latest
    name: Release Packaging MacOS
    env:
      ARCH: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ env.ARCH }}
      - name: Release Build
        run: |
          cargo build --release --target=${{ env.ARCH }} \
          && mv target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }} target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }} \
          && mv target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}.rlib target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
      - name: Upload lib Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}
          path: target/${{ env.ARCH }}/release/${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}
      - name: Upload bin Artifact
        uses: actions/upload-artifact@v2
        with:
          name: lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib  
          path: target/${{ env.ARCH }}/release/lib${{ env.PROJECT_NAME_UNDERSCORE }}-${{ env.ARCH }}.rlib
  
