on: workflow_call

name: Release

jobs:
  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME_UNDERSCORE: renvy
    steps:
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "${{ env.PROJECT_NAME_UNDERSCORE }}*,lib${{ env.PROJECT_NAME_UNDERSCORE }}*"
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true

  crates-io-release:
    name: Crates.io Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - run: cargo publish --token ${CRATES_TOKEN} --dry-run
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
