on:
  workflow_call:
    secrets:
      crates-token:
        description: 'Crates.io token to use for publishing'
        required: true

name: Release

jobs:
  github-release:
    name: GitHub Release
    runs-on: ubuntu-latest
    env:
      PROJECT_NAME_UNDERSCORE: renvy
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: deploy
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: deploy
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "deploy/*/*"
          artifactErrorsFailBuild: true
          draft: true
          generateReleaseNotes: true

  # crates-io-release:
  #   name: Crates.io Release
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - name: Install latest rust toolchain
  #       uses: actions-rs/toolchain@v1
  #       with:
  #         profile: minimal
  #         toolchain: stable
  #         override: true
  #     - name: Publish library librenvy to crates.io
  #       run: cargo publish --token ${{ secrets.crates-token }} -p librenvy --dry-run
  #     - name: Publish binary renvy to crates.io
  #       run: cargo publish --token ${{ secrets.crates-token }} -p librenvy --dry-run
