on: workflow_call

name: Test

env:
  PROJECT_NAME_UNDERSCORE: ${{ vars.PROJECT_NAME_UNDERSCORE }}

jobs:
  test:
    name: Test
    env:
      CARGO_INCREMENTAL: 0
      RUSTFLAGS: -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off
      RUSTDOCFLAGS: -Cpanic=abort
      RUST_BACKTRACE: full
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install latest stable rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
          RUST_BACKTRACE: 1
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Generate test result
        run: |
          cargo install cargo2junit;
          cargo test $CARGO_OPTIONS -- -Z unstable-options --format json | tee >(cargo2junit > results.xml)
      - name: Upload test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          check_name: Test Results
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: results.xml
